#pragma once
#include <cstdint>
#include <string>

namespace console
{
	struct Color
	{
		uint8_t r;
		uint8_t g;
		uint8_t b;
	};

	namespace color
	{
		extern const Color alice_blue;
		extern const Color antique_white;
		extern const Color aqua;
		extern const Color aquamarine;
		extern const Color azure;
		extern const Color beige;
		extern const Color bisque;
		extern const Color black;
		extern const Color blanched_almond;
		extern const Color blue;
		extern const Color blue_violet;
		extern const Color brown;
		extern const Color burly_wood;
		extern const Color cadet_blue;
		extern const Color chartreuse;
		extern const Color chocolate;
		extern const Color coral;
		extern const Color cornflower_blue;
		extern const Color cornsilk;
		extern const Color crimson;
		extern const Color cyan;
		extern const Color dark_blue;
		extern const Color dark_cyan;
		extern const Color dark_golden_rod;
		extern const Color dark_gray;
		extern const Color dark_green;
		extern const Color dark_khaki;
		extern const Color dark_magenta;
		extern const Color dark_olive_green;
		extern const Color dark_orange;
		extern const Color dark_orchid;
		extern const Color dark_red;
		extern const Color dark_salmon;
		extern const Color dark_sea_green;
		extern const Color dark_slate_blue;
		extern const Color dark_slate_gray;
		extern const Color dark_turquoise;
		extern const Color dark_violet;
		extern const Color deep_pink;
		extern const Color deep_sky_blue;
		extern const Color dim_gray;
		extern const Color dodger_blue;
		extern const Color fire_brick;
		extern const Color floral_white;
		extern const Color forest_green;
		extern const Color fuchsia;
		extern const Color gainsboro;
		extern const Color ghost_white;
		extern const Color gold;
		extern const Color golden_rod;
		extern const Color gray;
		extern const Color green;
		extern const Color green_yellow;
		extern const Color honey_dew;
		extern const Color hot_pink;
		extern const Color indian_red;
		extern const Color indigo;
		extern const Color ivory;
		extern const Color khaki;
		extern const Color lavender;
		extern const Color lavender_blush;
		extern const Color lawn_green;
		extern const Color lemon_chiffon;
		extern const Color light_blue;
		extern const Color light_coral;
		extern const Color light_cyan;
		extern const Color light_golden_rod_yellow;
		extern const Color light_gray;
		extern const Color light_green;
		extern const Color light_pink;
		extern const Color light_salmon;
		extern const Color light_sea_green;
		extern const Color light_sky_blue;
		extern const Color light_slate_gray;
		extern const Color light_steel_blue;
		extern const Color light_yellow;
		extern const Color lime;
		extern const Color lime_green;
		extern const Color linen;
		extern const Color magenta;
		extern const Color maroon;
		extern const Color medium_aquamarine;
		extern const Color medium_blue;
		extern const Color medium_orchid;
		extern const Color medium_purple;
		extern const Color medium_sea_green;
		extern const Color medium_slate_blue;
		extern const Color medium_spring_green;
		extern const Color medium_turquoise;
		extern const Color medium_violet_red;
		extern const Color midnight_blue;
		extern const Color mint_cream;
		extern const Color misty_rose;
		extern const Color moccasin;
		extern const Color navajo_white;
		extern const Color navy;
		extern const Color old_lace;
		extern const Color olive;
		extern const Color olive_drab;
		extern const Color orange;
		extern const Color orange_red;
		extern const Color orchid;
		extern const Color pale_golden_rod;
		extern const Color pale_green;
		extern const Color pale_turquoise;
		extern const Color pale_violet_red;
		extern const Color papaya_whip;
		extern const Color peach_puff;
		extern const Color peru;
		extern const Color pink;
		extern const Color plum;
		extern const Color powder_blue;
		extern const Color purple;
		extern const Color rebecca_purple;
		extern const Color red;
		extern const Color rosy_brown;
		extern const Color royal_blue;
		extern const Color saddle_brown;
		extern const Color salmon;
		extern const Color sandy_brown;
		extern const Color sea_green;
		extern const Color sea_shell;
		extern const Color sienna;
		extern const Color silver;
		extern const Color sky_blue;
		extern const Color slate_blue;
		extern const Color slate_gray;
		extern const Color snow;
		extern const Color spring_green;
		extern const Color steel_blue;
		extern const Color tan;
		extern const Color teal;
		extern const Color thistle;
		extern const Color tomato;
		extern const Color turquoise;
		extern const Color violet;
		extern const Color wheat;
		extern const Color white;
		extern const Color white_smoke;
		extern const Color yellow;
		extern const Color yellow_green;
	}

	void init();
	std::string fg(uint8_t r, uint8_t g, uint8_t b);
	std::string fg(const Color& color);
	std::string bg(uint8_t r, uint8_t g, uint8_t b);
	std::string bg(const Color& color);
	void clear();
	extern const std::string reset;
	extern const std::string bold;
	extern const std::string faint;
	extern const std::string italic;
	extern const std::string underline;
	extern const std::string blink;
	extern const std::string reverse;
	extern const std::string hide;
	extern const std::string strike;
	extern const std::string doubly;
}
